import React, { useMemo, useState } from 'react';
import { useShoppingGuideData } from '../hooks/useShoppingGuideData.js';
import { TRAVEL_TOOL_STYLES } from './TravelToolStyles.js';

const STYLES = `
.shop-hero{padding:22px;border-radius:22px;background:linear-gradient(135deg,#211a35,#7b3150);color:#fff;box-shadow:var(--shadow-card-lg)}.shop-hero__eyebrow{font-size:11px;font-weight:800;letter-spacing:1.2px;text-transform:uppercase;color:#f5c9d9}.shop-hero h2{font-size:27px;line-height:1.05;margin:7px 0}.shop-hero p{font-size:13px;line-height:1.5;color:rgba(255,255,255,.78);margin:0}.shop-hero__pills{display:flex;gap:7px;flex-wrap:wrap;margin-top:15px}.shop-hero__pills span{font-size:11px;padding:6px 9px;border:1px solid rgba(255,255,255,.2);border-radius:999px;background:rgba(255,255,255,.09)}
.shop-tabs{display:flex;gap:7px;overflow:auto;scrollbar-width:none;position:sticky;top:56px;z-index:3;padding:10px 0;background:var(--bg-primary)}.shop-tab{flex:none;border:1px solid var(--glass-border);background:var(--bg-surface);color:var(--label-secondary);border-radius:999px;padding:8px 12px;font:600 12px var(--font)}.shop-tab--active{background:var(--accent);border-color:var(--accent);color:#fff}.shop-section-title{font-size:19px;color:var(--label-primary);margin:18px 2px 4px}.shop-section-copy{color:var(--label-secondary);font-size:13px;line-height:1.5;margin:0 2px 12px}
.shop-gift{border-left:4px solid #be7a96}.shop-gift__top,.shop-store__top{display:flex;align-items:flex-start;gap:10px}.shop-gift__tier,.shop-store__name{font-size:16px;font-weight:750;color:var(--label-primary);flex:1}.shop-gift__budget{font-size:11px;color:var(--accent);font-weight:700}.shop-gift__pick{font-size:14px;font-weight:650;margin-top:9px;color:var(--label-primary)}.shop-gift p{font-size:13px;line-height:1.45;color:var(--label-secondary)}.shop-verdict{display:inline-block;background:rgba(190,122,150,.13);color:#a54d71;border-radius:8px;padding:5px 8px;font-size:11px;font-weight:800}
.watch-intro{border-left:4px solid #d8a72c}.watch-intro p,.watch-brand p,.watch-model p{font-size:13px;line-height:1.5;color:var(--label-secondary)}.watch-decision-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.watch-decision{padding:13px;border-radius:15px;background:var(--bg-surface);border:1px solid var(--glass-border)}.watch-decision__icon{font-size:22px}.watch-decision strong{display:block;color:var(--label-primary);font-size:13px;margin-top:5px}.watch-decision b{display:block;color:var(--accent);font-size:12px;margin-top:4px}.watch-decision p{color:var(--label-secondary);font-size:11px;line-height:1.4;margin:5px 0 0}.watch-brand__head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.watch-brand__head strong{font-size:17px;color:var(--label-primary)}.watch-brand__verdict{font-size:10px;color:#fff;background:var(--accent);border-radius:999px;padding:5px 7px;text-align:right}.watch-model{border-top:3px solid #d8a72c}.watch-model__head{display:flex;justify-content:space-between;gap:10px}.watch-model__brand{font-size:11px;color:var(--accent);font-weight:800;text-transform:uppercase}.watch-model__ref{font-size:17px;color:var(--label-primary);font-weight:800;margin-top:2px}.watch-model__nick{font-size:12px;color:var(--label-secondary);margin-top:2px}.watch-model__price{text-align:right;flex:none}.watch-model__price strong{display:block;font-size:16px;color:var(--label-primary)}.watch-model__price span{font-size:10px;color:var(--label-secondary)}.watch-specs{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin:11px 0}.watch-spec{padding:8px;border-radius:9px;background:var(--bg-secondary)}.watch-spec small{display:block;color:var(--label-secondary);font-size:9px;text-transform:uppercase}.watch-spec span{display:block;color:var(--label-primary);font-size:11px;margin-top:2px}.watch-model__tradeoff{padding:9px;border-radius:9px;background:rgba(232,0,45,.08)}.watch-model__bottom{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:10px}.watch-rank{display:flex;gap:12px;align-items:flex-start}.watch-rank__number{font-size:25px;color:var(--accent);font-weight:900}.watch-script__ja{display:block;font-size:15px;color:var(--label-primary);margin-top:5px}.watch-script__reading{display:block;font-size:11px;color:var(--accent);margin-top:2px}
.paper-pick{border-top:3px solid #7866d5}.paper-pick__type{font-size:10px;text-transform:uppercase;font-weight:800;color:#7866d5}.paper-pick h3{font-size:17px;color:var(--label-primary);margin:4px 0}.paper-pick__ref{font-size:11px;color:var(--label-secondary)}.paper-pick p,.used-hunt p{font-size:13px;line-height:1.48;color:var(--label-secondary)}.paper-target{padding:10px;border-radius:9px;background:rgba(120,102,213,.1)}.mission-card{display:grid;grid-template-columns:72px 1fr;gap:11px}.mission-card__budget{font-size:15px;font-weight:850;color:var(--accent)}.mission-card h3{font-size:15px;color:var(--label-primary);margin:0}.mission-card p{font-size:12px;color:var(--label-secondary);line-height:1.4}.used-hunt{border-left:4px solid #45a078}.used-hunt__head{display:flex;gap:9px;align-items:center}.used-hunt__icon{font-size:24px}.used-hunt h3{font-size:17px;color:var(--label-primary);margin:0}.used-verdict{padding:9px;border-radius:9px;background:rgba(69,160,120,.1)}
.shop-category-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.shop-category{border:1px solid var(--glass-border);background:var(--bg-surface);border-radius:16px;padding:14px;text-align:left;font-family:var(--font)}.shop-category--active{border:2px solid var(--accent);padding:13px}.shop-category__icon{font-size:23px}.shop-category__label{display:block;font-size:14px;font-weight:750;color:var(--label-primary);margin-top:6px}.shop-category__price{display:block;font-size:10px;color:var(--label-secondary);margin-top:3px}.shop-category-detail h3{font-size:12px;text-transform:uppercase;letter-spacing:.6px;color:var(--accent);margin:15px 0 6px}.shop-category-detail ul{padding-left:20px;margin:0;color:var(--label-secondary);font-size:13px;line-height:1.5}.shop-category-detail p{font-size:13px;color:var(--label-secondary);line-height:1.5}.shop-pro{padding:11px;border-radius:10px;background:rgba(0,122,255,.08)}
.shop-cta{width:100%;border:0;border-radius:12px;padding:12px;background:var(--accent);color:#fff;font:700 13px var(--font);text-align:left;cursor:pointer}
.shop-toolbar{display:grid;grid-template-columns:1fr auto;gap:8px;margin:12px 0}.shop-search,.shop-select,.shop-input{border:1px solid var(--glass-border);background:var(--bg-surface);color:var(--label-primary);border-radius:11px;padding:11px;font:13px var(--font);min-width:0}.shop-store__meta{font-size:11px;color:var(--accent);font-weight:700;margin-top:3px}.shop-store__why{font-size:13px;color:var(--label-secondary);line-height:1.45}.shop-store__hunt{font-size:13px;color:var(--label-primary);line-height:1.45;padding:9px 10px;border-radius:9px;background:var(--bg-secondary)}.shop-store__hunt strong{color:var(--accent)}.shop-store__tip{font-size:12px;color:var(--label-secondary);line-height:1.4}.shop-fav{border:0;background:transparent;font-size:22px;color:#b6b6bd;padding:0}.shop-fav--on{color:#e1a21a}.shop-actions{display:flex;gap:8px;margin-top:10px}.shop-link{border:1px solid var(--glass-border);border-radius:9px;padding:7px 10px;font-size:11px;font-weight:700;color:var(--accent);text-decoration:none}.shop-empty{text-align:center;padding:30px;color:var(--label-secondary)}
.shop-route__head{display:flex;justify-content:space-between;gap:10px}.shop-route__title{font-size:17px;font-weight:750;color:var(--label-primary)}.shop-route__duration{font-size:11px;color:var(--accent);font-weight:700}.shop-route ol{padding-left:23px;color:var(--label-primary);font-size:13px;line-height:1.65}.shop-route p{color:var(--label-secondary);font-size:13px;line-height:1.5}.shop-route__badge{display:inline-block;font-size:10px;font-weight:800;color:#fff;background:var(--accent);border-radius:999px;padding:4px 7px}
.shop-calc{background:linear-gradient(145deg,var(--bg-surface),var(--bg-secondary))}.shop-calc__grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.shop-field label{display:block;font-size:10px;text-transform:uppercase;color:var(--label-secondary);font-weight:700;margin:0 0 4px 2px}.shop-calc__result{text-align:center;padding:18px;margin-top:12px;border-radius:14px;background:#211a35;color:#fff}.shop-calc__result strong{display:block;font-size:28px}.shop-calc__result span{font-size:11px;color:rgba(255,255,255,.7)}.shop-switch{display:flex;align-items:center;gap:7px;font-size:12px;color:var(--label-secondary);margin-top:10px}.shop-warning{padding:12px;border-radius:11px;background:rgba(232,0,45,.1);color:var(--label-secondary);font-size:12px;line-height:1.45}.shop-rule{font-size:13px;color:var(--label-secondary);line-height:1.5}.shop-rule li+li{margin-top:6px}.shop-checks details summary{font-size:14px;font-weight:700;color:var(--label-primary);cursor:pointer}.shop-checks ul{padding-left:20px;color:var(--label-secondary);font-size:13px;line-height:1.55}.shop-source{display:block;margin:7px 0}.customs-hero{background:linear-gradient(135deg,#163c36,#246c5c);color:#fff}.customs-hero strong{display:block;font-size:28px}.customs-hero span{font-size:12px;color:rgba(255,255,255,.75)}.customs-example__case{font-weight:750;color:var(--label-primary)}.customs-example__approx{font-size:11px;font-weight:700;color:var(--accent);margin:3px 0 8px}.customs-example p{font-size:13px;line-height:1.45;color:var(--label-secondary);margin:0}.customs-no{border-left:4px solid #e8002d}@media(max-width:360px){.shop-category-grid,.shop-toolbar,.shop-calc__grid{grid-template-columns:1fr}}
`;

const TABS = [['gift','🎁 Para ella'],['watches','⌚ Reloj para papá'],['paper','✒️ Papelería premium'],['used','♻️ Segunda mano'],['discover','🛍️ Categorías'],['stores','📍 Tiendas'],['routes','🧭 Rutas'],['calculator','¥ Calculadora'],['rules','🛂 Tax-free + España']];

function GiftView({ data }) {
  return <><h2 className="shop-section-title">El detalle que sí parece lujo</h2><p className="shop-section-copy">Mi apuesta: papelería extraordinaria como regalo principal, o un small leather good pre-owned si aparece la pieza correcta. No persigas un bolso solo por el logo.</p>{data.gift_shortlist.map((g)=><article className="travel-card shop-gift" key={g.tier}><div className="shop-gift__top"><div className="shop-gift__tier">{g.tier}</div><div className="shop-gift__budget">{g.budget}</div></div><div className="shop-gift__pick">{g.pick}</div><p><strong>{g.where}.</strong> {g.why}</p><span className="shop-verdict">{g.verdict}</span></article>)}<div className="travel-card shop-warning"><strong>Consejo de novio:</strong> si no conoces modelo/color exacto, un pañuelo, tarjetero o papelería personalizada tiene mucho menos riesgo que un bolso. Pide envoltorio: 「プレゼント用にお願いします」.</div></>;
}

function WatchView({ data }) {
  const w=data.watch_guide;
  const [brand,setBrand]=useState('Todas');
  const visible=w.models.filter((model)=>brand==='Todas'||model.brand===brand);
  const euro=(yen)=>(yen/w.exchange_rate).toLocaleString('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0});
  return <><article className="travel-card watch-intro"><span className="shop-verdict">Guía verificada {w.verified_at}</span><h2 className="shop-section-title">{w.title}</h2><p>{w.opening}</p></article>
    <h2 className="shop-section-title">Primero decide qué hombre es</h2><div className="watch-decision-grid">{w.first_decision.map((x)=><article className="watch-decision" key={x.id}><span className="watch-decision__icon">{x.icon}</span><strong>{x.title}</strong><b>{x.answer}</b><p>{x.why}</p></article>)}</div>
    <h2 className="shop-section-title">Las preguntas que cambian la compra</h2><ol className="travel-card shop-rule">{w.questions.map((x)=><li key={x}>{x}</li>)}</ol>
    <h2 className="shop-section-title">Citizen vs Seiko vs Orient</h2>{w.brands.map((x)=><article className="travel-card watch-brand" key={x.name}><div className="watch-brand__head"><strong>{x.name}</strong><span className="watch-brand__verdict">{x.verdict}</span></div><p><b>Lo mejor:</b> {x.strength}</p><p><b>La trampa:</b> {x.weakness}</p><p><b>Para quién:</b> {x.best_for}</p></article>)}
    <h2 className="shop-section-title">Shortlist concreta</h2><p className="shop-section-copy">PVP japonés oficial con impuestos y neto tax-free teórico. El stock y descuentos de distribuidor se comprueban el día de compra.</p><div className="shop-tabs">{['Todas','Citizen','Seiko','Orient'].map((x)=><button className={`shop-tab ${brand===x?'shop-tab--active':''}`} onClick={()=>setBrand(x)} key={x}>{x}</button>)}</div>
    {visible.map((m)=><article className="travel-card watch-model" key={m.reference}><div className="watch-model__head"><div><div className="watch-model__brand">{m.brand} · {m.family}</div><div className="watch-model__ref">{m.reference}</div><div className="watch-model__nick">{m.nickname}</div></div><div className="watch-model__price"><strong>{euro(m.price_jpy_tax_free)}</strong><span>¥{m.price_jpy_tax_free.toLocaleString('es-ES')} netos</span></div></div><div className="watch-specs"><div className="watch-spec"><small>Movimiento</small><span>{m.movement}</span></div><div className="watch-spec"><small>Caja</small><span>{m.case}</span></div><div className="watch-spec"><small>Agua</small><span>{m.water}</span></div><div className="watch-spec"><small>Estilo</small><span>{m.style}</span></div></div><p><b>Encaja si:</b> {m.best_for}</p><p className="watch-model__tradeoff"><b>La contrapartida:</b> {m.tradeoff}</p><div className="watch-model__bottom"><span className="shop-verdict">{m.verdict}</span><a className="shop-link" href={m.url} target="_blank" rel="noreferrer">Ficha oficial ↗</a></div></article>)}
    <h2 className="shop-section-title">Mi ranking sin saber aún su muñeca</h2>{w.ranking.map((x)=><article className="travel-card watch-rank" key={x.place}><div className="watch-rank__number">{x.place}</div><div><div className="shop-store__name">{x.model}</div><p className="shop-rule">{x.reason}</p></div></article>)}
    <h2 className="shop-section-title">Ruta de compra en Ginza</h2><ol className="travel-card shop-rule">{w.buy_route.map((x)=><li key={x}>{x}</li>)}</ol>
    <h2 className="shop-section-title">Frases en la relojería</h2>{w.shop_script.map((x)=><article className="travel-card" key={x.es}><strong>{x.es}</strong><span className="watch-script__ja">{x.ja}</span><span className="watch-script__reading">{x.reading}</span></article>)}
    <h2 className="shop-section-title">Checklist en caja</h2><ul className="travel-card shop-rule">{w.final_check.map((x)=><li key={x}>{x}</li>)}</ul>
    <h2 className="shop-section-title">Fuentes oficiales</h2>{w.sources.map((s)=><a className="travel-source shop-source" href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.name} ↗</a>)}</>;
}

function PaperView({ data }) {
  const p=data.stationery_guide;
  const [type,setType]=useState('Todo');
  const types=['Todo',...new Set(p.picks.map((x)=>x.type))];
  const visible=p.picks.filter((x)=>type==='Todo'||x.type===type);
  const euro=(yen)=>(yen/p.exchange_rate).toLocaleString('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0});
  return <><article className="travel-card watch-intro"><span className="shop-verdict">Precios revisados {p.verified_at}</span><h2 className="shop-section-title">{p.title}</h2><p>{p.philosophy}</p></article>
    <h2 className="shop-section-title">¿Qué fantasía compramos?</h2><div className="watch-decision-grid">{p.profiles.map((x)=><article className="watch-decision" key={x.title}><span className="watch-decision__icon">{x.icon}</span><strong>{x.title}</strong><b>{x.budget}</b><p>{x.plan}</p></article>)}</div>
    <h2 className="shop-section-title">Seis reglas para proteger tu pasta</h2><ol className="travel-card shop-rule">{p.rules.map((x)=><li key={x}>{x}</li>)}</ol>
    <h2 className="shop-section-title">Objetos con nombre y precio</h2><div className="shop-tabs">{types.map((x)=><button className={`shop-tab ${type===x?'shop-tab--active':''}`} onClick={()=>setType(x)} key={x}>{x}</button>)}</div>{visible.map((x)=><article className="travel-card paper-pick" key={x.name}><div className="watch-model__head"><div><div className="paper-pick__type">{x.type} · {x.sweet_spot}</div><h3>{x.name}</h3><div className="paper-pick__ref">{x.reference}</div></div><div className="watch-model__price"><strong>{euro(x.price_jpy_net)}</strong><span>¥{x.price_jpy_net.toLocaleString('es-ES')} netos</span></div></div><p><b>Por qué:</b> {x.why}</p><p className="watch-model__tradeoff"><b>Ojo:</b> {x.watch_out}</p><p className="paper-target"><b>Mi umbral:</b> {x.target}</p><a className="shop-link" href={x.url} target="_blank" rel="noreferrer">Fuente / producto ↗</a></article>)}
    <h2 className="shop-section-title">{p.used_pen.title}</h2><article className="travel-card"><p className="shop-rule">{p.used_pen.why}</p><ul className="shop-rule">{p.used_pen.inspect.map((x)=><li key={x}>{x}</li>)}</ul></article>{p.used_pen.stores.map((x)=><article className="travel-card" key={x.name}><div className="shop-store__name">{x.name}</div><p className="shop-rule">{x.mission}</p><div className="shop-warning"><b>Riesgo:</b> {x.risk}</div><a className="shop-link" href={x.url} target="_blank" rel="noreferrer">Tienda ↗</a></article>)}
    <h2 className="shop-section-title">Cinco presupuestos cerrados</h2>{p.missions.map((x)=><article className="travel-card mission-card" key={x.budget}><div className="mission-card__budget">{x.budget}</div><div><h3>{x.name}</h3><p>{x.basket}</p><span className="shop-verdict">{x.verdict}</span></div></article>)}
    <h2 className="shop-section-title">Ruta de caza</h2><ol className="travel-card shop-rule">{p.route.map((x)=><li key={x}>{x}</li>)}</ol><h2 className="shop-section-title">Fuentes</h2>{p.sources.map((s)=><a className="travel-source shop-source" href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.name} ↗</a>)}</>;
}

function UsedView({ data }) {
  const u=data.preowned_guide;
  return <><article className="travel-card watch-intro"><h2 className="shop-section-title">{u.title}</h2><p>{u.opening}</p><p className="paper-target"><b>Regla de oro:</b> {u.golden_rule}</p></article>
    <h2 className="shop-section-title">Dónde está la oportunidad real</h2>{u.hunts.map((x)=><article className="travel-card used-hunt" key={x.category}><div className="used-hunt__head"><span className="used-hunt__icon">{x.icon}</span><div><h3>{x.category}</h3><div className="shop-store__meta">{x.where}</div></div></div><p><b>Caza:</b> {x.target}</p><p><b>Sweet spot:</b> {x.sweet}</p><p><b>Inspecciona:</b> {x.inspect}</p><p className="used-verdict">{x.walk}</p></article>)}
    <h2 className="shop-section-title">Descifra las etiquetas japonesas</h2>{u.condition_language.map((x)=><article className="travel-card" key={x.term}><div className="shop-store__name">{x.term}</div><p className="shop-rule">{x.meaning}</p></article>)}
    <h2 className="shop-section-title">Frenos de presupuesto</h2><ol className="travel-card shop-rule">{u.budget_guardrails.map((x)=><li key={x}>{x}</li>)}</ol><h2 className="shop-section-title">Fuentes</h2>{u.sources.map((s)=><a className="travel-source shop-source" href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.name} ↗</a>)}</>;
}

function DiscoverView({ data, onOpenWatches }) {
  const [selected,setSelected]=useState(data.categories[0]?.id); const c=data.categories.find((x)=>x.id===selected);
  return <><h2 className="shop-section-title">Compra como un local obsesivo</h2><p className="shop-section-copy">Cada categoría incluye sweet spot, qué merece la maleta y dónde están las trampas.</p><div className="shop-category-grid">{data.categories.map((x)=><button key={x.id} className={`shop-category ${selected===x.id?'shop-category--active':''}`} onClick={()=>setSelected(x.id)}><span className="shop-category__icon">{x.icon}</span><span className="shop-category__label">{x.label}</span><span className="shop-category__price">Sweet spot {x.sweet_spot}</span></button>)}</div>{c&&<article className="travel-card shop-category-detail">{c.id==='watches'&&<button className="shop-cta" onClick={onOpenWatches}>Abrir guía profunda Citizen · Seiko · Orient →</button>}<h3>Objetivos buenos</h3><ul>{c.buy.map((x)=><li key={x}>{x}</li>)}</ul><h3>Lo que no haría</h3><p>{c.avoid}</p><h3>Movimiento pro</h3><p className="shop-pro">{c.pro_move}</p></article>}</>;
}

function StoresView({ data }) {
  const [query,setQuery]=useState(''); const [category,setCategory]=useState('all'); const [favorites,setFavorites]=useState(()=>{try{return JSON.parse(localStorage.getItem('shopping_favorites')||'[]')}catch{return[]}});
  const visible=useMemo(()=>data.stores.filter((s)=>(category==='all'||s.category===category||(category==='favorites'&&favorites.includes(s.id)))&&`${s.name} ${s.area} ${s.city} ${s.hunt}`.toLowerCase().includes(query.toLowerCase())),[data.stores,category,favorites,query]);
  const toggle=(id)=>{const next=favorites.includes(id)?favorites.filter((x)=>x!==id):[...favorites,id];setFavorites(next);try{localStorage.setItem('shopping_favorites',JSON.stringify(next))}catch{}};
  return <><h2 className="shop-section-title">{data.stores.length} paradas escogidas</h2><p className="shop-section-copy">No es un directorio: son tiendas con una misión concreta. Guarda estrellas para tu shortlist.</p><div className="shop-toolbar"><input className="shop-search" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Tienda, barrio o producto…"/><select className="shop-select" value={category} onChange={(e)=>setCategory(e.target.value)}><option value="all">Todas</option><option value="favorites">★ Favoritas</option>{data.categories.map((c)=><option key={c.id} value={c.id}>{c.label}</option>)}</select></div>{visible.map((s)=><article className="travel-card" key={s.id}><div className="shop-store__top"><div><div className="shop-store__name">{s.name}</div><div className="shop-store__meta">{s.area} · {s.city} · {s.price}</div></div><button className={`shop-fav ${favorites.includes(s.id)?'shop-fav--on':''}`} onClick={()=>toggle(s.id)} aria-label="Guardar tienda">★</button></div><p className="shop-store__why">{s.why}</p><div className="shop-store__hunt"><strong>Caza:</strong> {s.hunt}</div><p className="shop-store__tip"><strong>Ojo:</strong> {s.tip}<br/><strong>Tax-free:</strong> {s.tax_free}</p><div className="shop-actions"><a className="shop-link" href={s.maps} target="_blank" rel="noreferrer">Cómo llegar ↗</a><a className="shop-link" href={s.url} target="_blank" rel="noreferrer">Web oficial ↗</a></div></article>)}{!visible.length&&<div className="shop-empty">No hay coincidencias.</div>}</>;
}

function RoutesView({ data }) { return <><h2 className="shop-section-title">Cuatro días de compras posibles</h2><p className="shop-section-copy">Para el 24 de agosto: elige una ruta, no intentes mezclarlas todas.</p>{data.routes.map((r)=><article className="travel-card shop-route" key={r.id}><div className="shop-route__head"><div><div className="shop-route__title">{r.title}</div><div className="shop-route__duration">{r.duration} · {r.best_for}</div></div><span className="shop-route__badge">{r.verdict}</span></div><ol>{r.stops.map((s)=><li key={s}>{s}</li>)}</ol><p>{r.strategy}</p></article>)}</>; }

function CalculatorView() {
  const [yen,setYen]=useState('30000'),[rate,setRate]=useState('185'),[taxFree,setTaxFree]=useState(true),[fee,setFee]=useState('0'); const net=taxFree?(Number(yen)||0)/1.1:(Number(yen)||0); const euros=(net/(Number(rate)||1))*(1+(Number(fee)||0)/100);
  return <><h2 className="shop-section-title">¿Es ganga de verdad?</h2><p className="shop-section-copy">Precio japonés con impuestos. No incluye una eventual liquidación al entrar en España.</p><article className="travel-card shop-calc"><div className="shop-calc__grid"><div className="shop-field"><label>Precio en ¥</label><input className="shop-input" inputMode="numeric" value={yen} onChange={(e)=>setYen(e.target.value)}/></div><div className="shop-field"><label>¥ por 1 €</label><input className="shop-input" inputMode="decimal" value={rate} onChange={(e)=>setRate(e.target.value)}/></div><div className="shop-field"><label>Comisión tarjeta %</label><input className="shop-input" inputMode="decimal" value={fee} onChange={(e)=>setFee(e.target.value)}/></div></div><label className="shop-switch"><input type="checkbox" checked={taxFree} onChange={(e)=>setTaxFree(e.target.checked)}/> Aplicar exención del 10% incluida</label><div className="shop-calc__result"><strong>{euros.toLocaleString('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:2})}</strong><span>{Math.round(net).toLocaleString('es-ES')} ¥ netos · antes de aduana</span></div></article><div className="travel-card shop-warning"><strong>Regla shopper:</strong> en tecnología exige al menos un 15% de ahorro después de comisiones. En vintage, paga por pieza + estado.</div></>;
}

function RulesView({ data }) {
  const customs=data.customs_spain;
  return <><h2 className="shop-section-title">1 · Tax-free en Japón</h2><h3 className="shop-section-copy">{data.tax_free.headline}</h3><ol className="travel-card shop-rule">{data.tax_free.steps.map((s)=><li key={s}>{s}</li>)}</ol>
    <h2 className="shop-section-title">2 · Aduanas al volver</h2><article className="travel-card customs-hero"><strong>{customs.allowance_eur} € por adulto</strong><span>{customs.status}</span><p>{customs.summary}</p></article>
    <h2 className="shop-section-title">Decisión en 30 segundos</h2><div className="shop-checks">{customs.decision_flow.map((step)=><details className="travel-card" key={step.question}><summary>{step.question}</summary><p className="shop-rule">{step.answer}</p></details>)}</div>
    <h2 className="shop-section-title">Cómo optimizar legalmente</h2><ol className="travel-card shop-rule">{customs.legal_optimization.map((x)=><li key={x}>{x}</li>)}</ol>
    <h2 className="shop-section-title">Ejemplos para este viaje</h2>{customs.examples.map((x)=><article className="travel-card customs-example" key={x.case}><div className="customs-example__case">{x.case}</div><div className="customs-example__approx">{x.approx}</div><p>{x.result}</p></article>)}
    <h2 className="shop-section-title">En el aeropuerto español</h2><ol className="travel-card shop-rule">{customs.airport.map((x)=><li key={x}>{x}</li>)}</ol>
    <article className="travel-card"><div className="customs-example__case">{customs.cost_formula.headline}</div><p className="shop-rule">{customs.cost_formula.formula}</p><div className="shop-warning">{customs.cost_formula.warning}</div></article>
    <h2 className="shop-section-title">Lo que no funciona</h2><ul className="travel-card shop-rule customs-no">{customs.never_do.map((x)=><li key={x}>{x}</li>)}</ul>
    <h2 className="shop-section-title">Checklist antes de pagar</h2><div className="shop-checks">{Object.entries(data.checklists).map(([key,list])=><details className="travel-card" key={key}><summary>{key==='luxury'?'👜 Lujo pre-owned':key==='watch'?'⌚ Reloj':'📷 Tecnología'}</summary><ul>{list.map((x)=><li key={x}>{x}</li>)}</ul></details>)}</div>
    <h2 className="shop-section-title">Fuentes oficiales</h2>{[...data.tax_free.sources,...customs.sources,...data.sources].filter((s,i,a)=>a.findIndex((x)=>x.url===s.url)===i).map((s)=><a className="travel-source shop-source" href={s.url} target="_blank" rel="noreferrer" key={s.url}>{s.name} ↗</a>)}</>;
}

export default function ShoppingGuideView({ onBack }) {
  const {data,loading,error}=useShoppingGuideData(); const [tab,setTab]=useState('gift');
  return <div className="travel-tool"><style>{TRAVEL_TOOL_STYLES}{STYLES}</style><nav className="travel-tool__nav"><button className="travel-tool__back" onClick={onBack}>‹ Volver</button><h1 className="travel-tool__title">Guía de compras</h1></nav><main className="travel-tool__body">{loading&&<div className="travel-loading">Preparando la ruta de compras…</div>}{error&&<div className="travel-warning">No se pudo cargar: {error}</div>}{data&&<><section className="shop-hero"><div className="shop-hero__eyebrow">Chelis · shopper edition</div><h2>Compra menos.<br/>Encuentra mejor.</h2><p>Relojes, papelería, tecnología, moda japonesa y regalos que sí vas a recordar.</p><div className="shop-hero__pills"><span>{data.stores.length} tiendas</span><span>{data.categories.length} categorías</span><span>Verificado {data.last_verified_at}</span></div></section><div className="shop-tabs">{TABS.map(([id,label])=><button className={`shop-tab ${tab===id?'shop-tab--active':''}`} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>{tab==='gift'&&<GiftView data={data}/>} {tab==='watches'&&<WatchView data={data}/>} {tab==='paper'&&<PaperView data={data}/>} {tab==='used'&&<UsedView data={data}/>} {tab==='discover'&&<DiscoverView data={data} onOpenWatches={()=>setTab('watches')}/>} {tab==='stores'&&<StoresView data={data}/>} {tab==='routes'&&<RoutesView data={data}/>} {tab==='calculator'&&<CalculatorView/>} {tab==='rules'&&<RulesView data={data}/>}</>}</main></div>;
}
